spring:
  freemarker:
    cache:  false # Whether to enable template caching.
    #设置前缀名
    prefix: /
    #设置模板后缀名
    suffix: .html
    allow-request-override: false  #Whether HttpServletRequest attributes are allowed to override (hide) controller generated model attributes of the same name.
    allow-session-override: false  # Whether HttpSession attributes are allowed to override (hide) controller generated model attributes of the same name.
    charset: UTF-8 # Template encoding.
    check-template-location: true # Whether to check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true  # 是否启用freemarker模板引擎
    expose-request-attributes: false  # Whether all request attributes should be added to the model prior to merging with the template.
    expose-session-attributes: false # Whether all HttpSession attributes should be added to the model prior to merging with the template.
    expose-spring-macro-helpers: true # Whether to expose a RequestContext for use by Spring's macro library, under the name "springMacroRequestContext".
    prefer-file-system-access: true #是否选择文件系统访问来加载模板。文件系统访问支持对模板更改的热检测。
    #settings:  freemarker 配置
    request-context-attribute: request  #RequestContext 对象别名
    template-loader-path:
    - classpath:/templates/
   
  mvc: 
    static-path-pattern: /templates/** #静态资源路径
  application:
    name: PrivateFileSystem
server:
  port: 80
  
